name: ${project.artifactId}
main: de.iani.cubesidestats.CubesideStatistics
version: ${project.version}-${build.number}
description: CubesideStatistics
authors:
  - Brokkonaut
api-version: 1.13
folia-supported: true
depend: [PlayerUUIDCache, CubesideSettings, CubesideUtils]
# loadbefore: [Vault]
